spring.application.name=api-gateway

server.port=8080

#Routing per auth
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

#Routing per payment
spring.cloud.gateway.server.webflux.routes[1].id=payment-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/payments/**

#Routing per assistant
spring.cloud.gateway.server.webflux.routes[2].id=assistant-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/assistant/**

#Routing per parking
spring.cloud.gateway.server.webflux.routes[3].id=parking-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/parking-spots/**

#Routing per routing jo emri me i mire ?
spring.cloud.gateway.server.webflux.routes[4].id=routing-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/routing/**

